### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] storeFileLocally is not defined

### ISSUE THREAD

**Issue by VladislavG** [NyllRE/nuxt-file-storage#3] opened 2024-04-25 16:04 UTC
[nuxt] [request error] [unhandled] [500] storeFileLocally is not defined 
What did I do wrong?

**Comment by NyllRE** [comment] 2024-04-25 17:27
could you provide more details and/or reproduction using stackblitz or codesandbox?

**Comment by NyllRE** [comment] 2024-04-25 17:35
I believe the issue is that you didn't import the function from the library

**Comment by VladislavG** [comment] 2024-04-25 18:39
I'm just starting to learn Nuxt, could you help? I need a solution to upload files to the server, I used the code from your example, but it doesn't work.. How do I import the storeFileLocally function from your library? I did everything your way Readme.md

**Comment by NyllRE** [comment] 2024-04-25 20:09
hey @VladislavG , I realized there is an issue with importing. you did everything right and it's a problem on my end so I will be fixing that and I will let you know when it's working

**Comment by VladislavG** [comment] 2024-04-26 09:37
Thanks!

**Comment by NyllRE** [comment] 2024-04-26 13:53
Hey @VladislavG , I have just fixed the issue and it should be automatically imported now, please update the package to v0.2.2 and check and tell me if you find any other issues so I can close this issue.

**Comment by NyllRE** [comment] 2024-04-26 14:04
also since you are new to nuxt feel free to reach out to me on any nuxt topic in general!

**Comment by VladislavG** [comment] 2024-04-27 07:20
Hi! Thanks! The function is being imported now, but another error has appeared, maybe I'm doing something wrong..

[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'split')
  at parseDataUrl (E:\Programms\OpenServer\OpenServer\domains\nuxt\node_modules\nuxt-file-storage\dist\runtime\server\utils\storage.mjs:26:20)
  at storeFileLocally (E:\Programms\OpenServer\OpenServer\domains\nuxt\node_modules\nuxt-file-storage\dist\runtime\server\utils\storage.mjs:4:33)
  at <anonymous> (E:\Programms\OpenServer\OpenServer\domains\nuxt\server\api\files.ts:4:1)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.handler (/E:/Programms/OpenServer/OpenServer/domains/nuxt/node_modules/h3/dist/index.mjs:1697:19)
  at async Server.toNodeHandle (/E:/Programms/OpenServer/OpenServer/domains/nuxt/node_modules/h3/dist/index.mjs:1907:7)

**Comment by VladislavG** [comment] 2024-04-27 08:54
I understand that the error occurs in the storage.mjs file in the parseDataUrl function because the argument of the file function is empty.

**Comment by NyllRE** [comment] 2024-04-27 09:49
could you give me the code or a reproduction?

**Comment by NyllRE** [comment] 2024-04-27 09:49
also tell me what file did you try to upload

**Comment by VladislavG** [comment] 2024-04-28 20:14
I will use Laravel in my projects. There are no such difficulties in PHP..

**Comment by NyllRE** [comment] 2024-04-28 21:55
I understand, this library is still very new and only maintained by me so I apologize for the inconvenience, if you could just help me understand what the issue you were facing is so I can solve it I would very much appreciate it, otherwise I will just close this issue

**Comment by NyllRE** [comment] 2024-05-09 04:06
closing this issue for lack of information on the issue

**Closed by NyllRE** 2024-05-09 04:06 UTC
